stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/abspen1
        ln -s `pwd` /go/src/github.com/abspen1/go-backend
        cd /go/src/github.com/abspen1/go-backend
        export GO111MODULE="on"
        ls -l
        go mod download
        go build -o bin/main
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: austin-api:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./austin-api-dc-svc-ingress.yaml