apiVersion: apps/v1
kind: Deployment
metadata:
  name: austinapi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: austinapi
  template:
    metadata:
      labels:
        app: austinapi
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: austinapi
          image: ${CICD_IMAGE}:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8558
              protocol: TCP
          env:
            - name: CICD_GIT_COMMIT
              value: ${CICD_GIT_COMMIT}
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASS
                  name: redis-pass
            - name: REDIS_HOST_PORT
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST_PORT
                  name: redis-pass
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: redis-pass
            - name: BACK-END-AUTH
              valueFrom:
                secretKeyRef:
                  key: BACK-END-AUTH
                  name: go-back-end
            - name: CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: CONSUMER_KEY
                  name: go-back-end
            - name: CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: CONSUMER_SECRET
                  name: go-back-end
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  key: EMAIL
                  name: go-back-end
            - name: EMAIL-PASS
              valueFrom:
                secretKeyRef:
                  key: EMAIL-PASS
                  name: go-back-end
            - name: KEY
              valueFrom:
                secretKeyRef:
                  key: KEY
                  name: go-back-end
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD-TEST
                  name: go-back-end
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  key: SECRET
                  name: go-back-end
            - name: APCA_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: APCA_API_KEY_ID
                  name: go-back-end
            - name: APCA_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: APCA_API_SECRET_KEY
                  name: go-back-end
            - name: api-key
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: python-emailer-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
spec:
  type: ClusterIP
  ports:
    - name: austin-api-port
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: austinapi

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: api-ingress
  namespace: api
spec:
  rules:
    - host: www.guldentech.com
      http:
        paths:
          - path: /austinapi
            backend:
              serviceName: api-service
              servicePort: austin-api-port
    - host: guldentech.com
      http:
        paths:
          - path: /austinapi
            backend:
              serviceName: api-service
              servicePort: austin-api-port
