apiVersion: apps/v1
kind: Deployment
metadata:
  name: austinapi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: austinapi
  template:
    metadata:
      labels:
        app: austinapi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: austinapi
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8558
          protocol: TCP
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-pass
        - name: REDIS_HOST_PORT
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST_PORT
              name: redis-pass
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-pass
        - name: BACK-END-AUTH
          valueFrom:
            secretKeyRef:
              key: BACK-END-AUTH
              name: go-back-end
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: CONSUMER_KEY
              name: go-back-end
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: CONSUMER_SECRET
              name: go-back-end
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              key: EMAIL
              name: go-back-end
        - name: EMAIL-PASS
          valueFrom:
            secretKeyRef:
              key: EMAIL-PASS
              name: go-back-end
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: KEY
              name: go-back-end
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD-TEST
              name: go-back-end
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: SECRET
              name: go-back-end

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
spec:
  type: ClusterIP
  ports:
    - name: austin-api-port
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: austinapi

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: api-ingress
  namespace: api
spec:
  rules:
    - host: www.guldentech.com
      http:
        paths:
          - path: /austinapi
            backend:
              serviceName: api-service
              servicePort: austin-api-port
    - host: guldentech.com
      http:
        paths:
          - path: /austinapi
            backend:
              serviceName: api-service
              servicePort: austin-api-port